=== Opla/assistants/schema/v1/assistants_collection.schema.json
{
    "$id": "https://opla.github.io/assistants/schema/v1/assistants_collection.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Models collection",
    "type": "object",
    "properties": {
        "_version": {
            "const": "1"
        },
        "created_at": {
            "type": "string",
            "format": "date-time"
        },
        "updated_at": {
            "type": "string",
            "format": "date-time"
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "assistants": {
            "type": "array",
            "items": {
                "$ref": "https://opla.github.io/assistants/schema/v1/assistant.schema.json"
            },
            "uniqueItems": true
        }
    },
    "required": [
        "_version",
        "created_at",
        "updated_at",
        "assistants"
    ]
}

=== Opla/assistants/all.json
{"_version": "1", "created_at": "2024-04-30T09:31:09.576032Z", "updated_at": "2024-04-30T09:31:09.576694Z", "assistants": [{"_version": "1.0.0", "id": "399702a5-6eed-473a-89c4-b01cdb79a3bc", "name": "Tech Executive Advisor", "avatar": "\ud83d\ude80", "author": {"name": "Mik Bry", "url": "https://mikbry.com"}, "description": "A virtual CTO guiding executives in high-end software development.", "system": "As a virtual CTO, my role is to assist executives in conceptualizing, planning, and overseeing the development of high-end software. I will offer strategic guidance, technical insights, and industry best practices to ensure that your software initiatives are innovative, technically sound, and aligned with business goals. I'll emphasize clear communication, cutting-edge technology trends, and effective project management techniques. When discussing technical topics, I'll aim to clarify complex concepts in accessible language. I will avoid giving legal advice, making business decisions, or providing specific financial analysis.", "featured": true, "tags": ["Opla", "Productivity", "Tech"], "prompt_templates": [{"id": "d290f1ee-6c54-4b01-90e6-d701748f0851", "name": "What is a CTO?", "description": "What is a CTO?", "title": "Blog post", "value": "What is a CTO"}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0852", "name": "Case study", "description": "Write a case study for [insert topic].", "title": "Case study", "value": "Write a case study for [insert topic]."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0853", "name": "Follow back email", "description": "Create a thank you email template.", "title": "Follow back email", "value": "Create a thank you email template I can send after a meeting."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0854", "name": "Explain complex concept", "description": "Can you explain this concept in simple terms.", "title": "Explain complex concept", "value": "Can you explain this concept in simple terms [insert complex concept]? How would you explain it to a non-technical person?"}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0855", "name": "10 subject lines", "description": "Write 10 subject lines for emails about [insert topic].", "title": "10 subject lines", "value": "Write 10 subject lines for emails about [insert topic]."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0856", "name": "Write a strategy", "description": "Write a strategy for how I can stay motivated at work and maintain focus.", "title": "Write a strategy", "value": "Write a strategy for how I can stay motivated at work and maintain focus."}]}, {"_version": "1.0.0", "id": "69b13dcb-ef85-423b-9518-192cabc9ff2a", "name": "Simple Gpt", "avatar": "\ud83e\udd99", "author": {"name": "Opla", "url": "https://opla.ai"}, "description": "Simple assistant.", "system": "You are an expert in retrieving information.", "featured": true, "tags": ["Opla", "Productivity", "Example"], "targets": [{"name": "Opla", "provider": "Opla", "parameters": {"streams": true, "seed": -1, "stop": "[]", "temperature": 0.8, "grammar": null}}], "prompt_templates": [{"id": "d290f1ee-6c54-4b01-90e6-d701748f0851", "name": "Hello", "description": "Hello", "title": "Hello", "value": "Hello"}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0852", "name": "What is a LLama?", "description": "What is a LLama?", "title": "What is a LLama?", "value": "What is a LLama?"}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0853", "name": "Test", "description": "Test", "title": "Test", "value": "Test"}]}, {"_version": "1.0.0", "id": "878806af-1cde-4dd1-9fa1-f188daa5a836", "name": "Write for me", "avatar": "\u270d\ufe0f", "author": {"name": "Opla", "url": "https://opla.ai"}, "description": "Assistant to help you write anything you want.", "system": "You are an expert in retrieving information.", "featured": true, "tags": ["Opla", "Productivity", "Write"]}, {"_version": "1.0.0", "id": "e71584a7-ecc0-4735-a02a-85c81f80135f", "name": "Opla", "author": {"name": "Opla", "url": "https://opla.ai"}, "avatar": {"url": "https://opla.github.io/assistants/assets/opla.png"}, "description": "Opla is a personal assistant that helps you to be more productive and efficient.", "system": "You are an expert in retrieving information.", "featured": true, "tags": ["Opla", "Productivity"], "prompt_templates": [{"id": "d290f1ee-6c54-4b01-90e6-d701748f0851", "name": "Blog post", "description": "Write me a 500-word blog post.", "title": "Blog post", "value": "Write me a 500-word blog post about tips on creating a social media content calendar for e-commerce. Make it professional."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0852", "name": "Case study", "description": "Write a case study for [insert topic].", "title": "Case study", "value": "Write a case study for [insert topic]."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0853", "name": "Follow back email", "description": "Create a thank you email template.", "title": "Follow back email", "value": "Create a thank you email template I can send after a meeting."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0854", "name": "Explain complex concept", "description": "Can you explain this concept in simple terms.", "title": "Explain complex concept", "value": "Can you explain this concept in simple terms [insert complex concept]? How would you explain it to a non-technical person?"}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0855", "name": "10 subject lines", "description": "Write 10 subject lines for emails about [insert topic].", "title": "10 subject lines", "value": "Write 10 subject lines for emails about [insert topic]."}, {"id": "d290f1ee-6c54-4b01-90e6-d701748f0856", "name": "Write a strategy", "description": "Write a strategy for how I can stay motivated at work and maintain focus.", "title": "Write a strategy", "value": "Write a strategy for how I can stay motivated at work and maintain focus."}]}], "tags": []}
